-- UPDATE JOB STATUS ENUM TO SUPPORT DYNAMIC PRICING
-- Run this in Supabase SQL Editor

ALTER TYPE "JobStatus" ADD VALUE IF NOT EXISTS 'ESTIMATE_SUBMITTED';
ALTER TYPE "JobStatus" ADD VALUE IF NOT EXISTS 'INSPECTION_REQUESTED';
ALTER TYPE "JobStatus" ADD VALUE IF NOT EXISTS 'INSPECTION_PAYMENT_PENDING';
